### PR TITLE
replace Sweep.kr with functions

### PR DESCRIPTION
**Pull request by nhthn**
no change to composition, just a code enhancement.

### CODE REVIEW

**Comment by nhthn** [comment]
@keypulsations ping

**Comment by keypulsations** [comment]
@snappizz sorry that I missed this! I'll looking forward to spending more time on this project and really appreciate your input. I was working on a similar refactoring with Sweep locally, but your change might be better. I'll push that up in a bit to see what you think.

I'm working to remove a lot of code duplication and to combine the two play methods into one overall piece of music. I'd love to hear some of your musical ideas too.

**Comment by nhthn** [comment]
@keypulsations A more serious refactor I would suggest is splitting it into multiple SynthDefs and using patterns instead of Demand ugens. (By the way, I used to be backseatviolist.)

**Comment by keypulsations** [comment]
@snappizz I think that's a good suggestion. I typically work with patterns, but I liked the idea of creating music from a single synth. I'll continue to group elements together and merge in your changes. 

I might also move some other files I'm working on in here to collaborations.git:

https://github.com/keypulsations/studies

**Comment by keypulsations** [comment]
@snappizz also nice to know that you were backseatviolist!

In general, what do you think of the idea of group collaboration on music works via Github (as if it were any other software)?

**Comment by nhthn** [comment]
@keypulsations I think it works great, but there's a limitation: git is intended to work with plain-text source code files. Although I'll gladly proclaim the benefits of text formats over graphical editors with binary formats, I understand that code intimidates many musicians, which unfortunately restricts the potential for git-based collaborative music to reach a wide audience.

LilyPond users have done similar things, taking advantage of its textual input format to organize "crowd transcriptions" of scores. I don't think there are any collaborative composition projects in LilyPond, though (mostly because LilyPond is not generally regarded as a composing tool). But the parallels are interesting anyway.

**Pull request merged**
